#!/bin/bash

command -v jq || { echo "Could not find jq. More info: https://github.com/stedolan/jq/wiki/Installation"; exit 1; }

SETTINGS_DIR="$PWD/.vscode"
SETTINGS="$SETTINGS_DIR/settings.json"
if [ -f "$SETTINGS" ]
then
    echo $(jq 'del(."docker.host")' $SETTINGS) > $SETTINGS
    echo $(jq 'del(."docker.certPath")' $SETTINGS) > $SETTINGS
    echo $(jq 'del(."docker.machineName")' $SETTINGS) > $SETTINGS
    echo $(jq 'del(."docker.tlsVerify")' $SETTINGS) > $SETTINGS
fi
