version: "3"
services:
  ${DEVCONTAINER_NAME}-base:
    image: ${DEVCONTAINER_NAME}-base
    env_file:
        - env
    build:
      context: ..
      dockerfile: ext-dev.Dockerfile
  ${DEVCONTAINER_NAME}:
    depends_on: [ "${DEVCONTAINER_NAME}-base" ]
    image: ${DEVCONTAINER_NAME}
    environment: 
        - DEVCONTAINER_NAME=${DEVCONTAINER_NAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - USER_NAME=${USER_NAME}
    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile
    volumes:
      - $PWD/extension:/workspaces/devcontainer-ext-dev
      - $PWD/test-workspace:/workspaces/test-workspace
    command: /bin/sh -c "while sleep 1000; do :; done"