name: Release
on:
  release:
    types: [edited, published]
    branches:
      - main
      - feature-*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Build
        env:
          PACKAGE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          ./build.sh
      - name: Publish binaries  
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'devcontainer_*_all.deb'